@token =  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ2aXJ0dWFsQ3J5cHRvIiwiZXhwIjoxNjE0NTAxNTUzLCJpYXQiOjE2MTQ0OTc5NTMsImlzcyI6InZpcnR1YWxDcnlwdG8iLCJqdGkiOiJlZWJmZWM4NS01M2M1LTQ2ZmYtOGVmYy01NzIyYWFhY2VhMDAiLCJraW5kIjoidXNlciIsIm5iZiI6MTYxNDQ5Nzk1Miwic2NvcGVzIjpbIm9hdXRoMi5yZWdpc3RlciIsInZjLnBheSIsInZjLmNsYWltIl0sInN1YiI6IjEiLCJ0eXAiOiJhY2Nlc3MifQ.FDjMsZlJnEUdKmTbccPNXNm2lY7BjRTsuaOhd4mJB2Sk3FnKwfWll7nGSUT23Ja81dkdw0SCWGAloI0jK__NLw
###
POST https://localhost:4000/oauth2/token/revoke
Content-Type: application/x-www-form-urlencoded

token={{token}}