POST https://localhost:4000/oauth2/clients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ2aXJ0dWFsQ3J5cHRvIiwiZXhwIjoxNjE0MzQ4MTMwLCJpYXQiOjE2MTQzNDQ1MzAsImlzcyI6InZpcnR1YWxDcnlwdG8iLCJqdGkiOiI5ZDVhNjE0OS1jNmIzLTQ4ZmQtOGY2Yy1kZWU4MjE3OTdiODIiLCJraW5kIjoidXNlciIsIm5iZiI6MTYxNDM0NDUyOSwic2NvcGVzIjpbIm9hdXRoMi5yZWdpc3RlciIsInZjLnBheSIsInZjLmNsYWltIl0sInN1YiI6IjEiLCJ0eXAiOiJhY2Nlc3MifQ.bACCtTkO7Z9_4nMr55YSCK1rhYn8DBvh_e-wDZIddYDzr4sHrbyhF1zQAwkQBeQEmgMJE1cd41vaCNcR37Yl7A

{
  "redirect_uris" : [],
  "client_name": "にゃーん",
  "logo_uri" : "https://lh3.googleusercontent.com/ogw/ADGmqu9aMzSjNmL4WfeJARzpKcPsQHkV77YlUxBIqcTI=s32-c-mo"
}