POST https://localhost:4000/oauth2/clients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ2aXJ0dWFsQ3J5cHRvIiwiZXhwIjoxNjE0MzQwNDQzLCJpYXQiOjE2MTQzMzY4NDMsImlzcyI6InZpcnR1YWxDcnlwdG8iLCJqdGkiOiIxNzUyOWU2Ny02ZTkwLTQ1ZjktYWQxMS02Yzk2MzI4YzczNzUiLCJraW5kIjoidXNlciIsIm5iZiI6MTYxNDMzNjg0Miwic2NvcGVzIjpbIm9hdXRoMi5yZWdpc3RlciIsInZjLnBheSIsInZjLmNsYWltIl0sInN1YiI6IjEiLCJ0eXAiOiJhY2Nlc3MifQ.siRkIe0WvGwUZelve1O9IJc5sNT9jRzeH-Q_CHQ8OV3QxB0o4jDwxgNoQ_Xduy9x0wW3MeO1qd4rHuh_fVuX-Q 

{
  "redirect_uris" : []
}