GET https://localhost:4000/api/v2/users/@me/claims
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ2aXJ0dWFsQ3J5cHRvIiwiZXhwIjoxNjI3NzI2ODQwLCJpYXQiOjE2Mjc3MjMyNDAsImlzcyI6InZpcnR1YWxDcnlwdG8iLCJqdGkiOiI0M2NhMjZkZi05ZjhjLTRmZjctODU5ZS1mZTQzMDhmY2MxZTYiLCJraW5kIjoidXNlciIsIm5iZiI6MTYyNzcyMzIzOSwic2NvcGVzIjpbIm9hdXRoMi5yZWdpc3RlciIsInZjLnBheSIsInZjLmNsYWltIl0sInN1YiI6IjEiLCJ0eXAiOiJhY2Nlc3MifQ.yLlQTK19X-jk4HYEMWE23RE1pLJ3aLvv7uDEAFhUbUjaoTYxQp4ColMIH8rS-5m5JLG1BVTnTMH5XVFsDCjm3g