GET https://localhost:4000/api/v1/users/@me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ2aXJ0dWFsQ3J5cHRvIiwiZXhwIjoxNjE0MzQxOTI2LCJpYXQiOjE2MTQzMzgzMjYsImlzcyI6InZpcnR1YWxDcnlwdG8iLCJqdGkiOiI2ZTFlNDExZS01ZmU0LTQ2MWMtOGU0Ny0wZGIxN2JhMjllMWYiLCJraW5kIjoiYXBwIiwibmJmIjoxNjE0MzM4MzI1LCJzY29wZXMiOlsidmMucGF5Il0sInN1YiI6IjQiLCJ0eXAiOiJhY2Nlc3MifQ.0kibBOAtWc0bUXGoqylbYxTwt2RRFEgB9E7d-rZnWplwjHS0f_RiRnoBIypxJL4gRSQVR3tlGaSHvDyuFCZCMQ